In [1]:
import sys
!{sys.executable} -m pip install pandas

Requirement already satisfied: pandas in /home/mp/Documents/edu/dtu/master/4-sem/02285_ai_and_mas/02285_vAIkings/mas-env/lib/python3.8/site-packages (1.0.3)
Requirement already satisfied: pytz>=2017.2 in /home/mp/Documents/edu/dtu/master/4-sem/02285_ai_and_mas/02285_vAIkings/mas-env/lib/python3.8/site-packages (from pandas) (2020.1)
Requirement already satisfied: numpy>=1.13.3 in /home/mp/Documents/edu/dtu/master/4-sem/02285_ai_and_mas/02285_vAIkings/mas-env/lib/python3.8/site-packages (from pandas) (1.18.4)
Requirement already satisfied: python-dateutil>=2.6.1 in /home/mp/Documents/edu/dtu/master/4-sem/02285_ai_and_mas/02285_vAIkings/mas-env/lib/python3.8/site-packages (from pandas) (2.8.1)
Requirement already satisfied: six>=1.5 in /home/mp/Documents/edu/dtu/master/4-sem/02285_ai_and_mas/02285_vAIkings/mas-env/lib/python3.8/site-packages (from python-dateutil>=2.6.1->pandas) (1.14.0)
WARNING: You are using pip version 20.0.2; however, version 20.1.1 is available.
You should consider upgrading via the '/home/mp/Documents/edu/dtu/master/4-sem/02285_ai_and_mas/02285_vAIkings/mas-env/bin/python -m pip install --upgrade pip' command.

In [2]:
import pandas as pd

In [3]:
master_df = pd.read_csv("master-summary.csv")
staging_df = pd.read_csv("staging-summary.csv")
improvements_df = pd.read_csv("improvements-summary.csv")
no_cnet_df = pd.read_csv("no-cnet-improved-summary.csv")

In [5]:
no_cnet_df[no_cnet_df['lvl_solved'] == 'No.'].sort_values("lvl_name")

       lvl_name lvl_solved  actions_used  last_action_time (in seconds)
30   MADeepPlan        No.      106043.0                         90.000
47     MAGLaDOS        No.          48.0                         89.560
45       MAIIOO        No.        9983.0                         89.996
7       MAKaren        No.         527.0                         89.989
0       MAMulle        No.       46275.0                         89.995
20    MANicolAI        No.       23934.0                         89.998
50     MAReftAI        No.           4.0                         57.131
53   MASokoBros        No.        4423.0                         89.986
33     MATheZoo        No.        5902.0                         89.991
5    MAaiaicapn        No.         442.0                         89.603
31  SAAIcaramba        No.      545454.0                         90.000
14  SABaguettes        No.        1001.0                         88.797
40  SABoxAgents        No.        1211.0                         89.940
56  SADeepMinds        No.       11622.0                         89.994
26     SAFPHPOP        No.         382.0                         86.201
52     SAGLaDOS        No.          61.0                         89.953
44     SAHoldUd        No.          93.0                         89.317
3       SAMulle        No.       26845.0                         89.998
22     SAReftAI        No.          67.0                         86.537
34   SASokoBros        No.        7666.0                         89.996
25     SATheZoo        No.         148.0                          0.250
54  SAfootsteps        No.      174664.0                         90.000